version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: smarttasker-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - smarttasker-network
    restart: unless-stopped

  # MongoDB Admin Interface
  mongo-express:
    image: mongo-express:latest
    container_name: smarttasker-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    networks:
      - smarttasker-network
    depends_on:
      - mongodb
    restart: unless-stopped

  # Redis Service
  redis:
    image: redis:alpine
    container_name: smarttasker-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - smarttasker-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Redis Commander - Redis Admin Interface
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: smarttasker-redis-commander
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=password
    networks:
      - smarttasker-network
    depends_on:
      - redis
    restart: unless-stopped

networks:
  smarttasker-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: 