version: '3.8'

services:
  # Redis Service
  redis:
    image: redis:alpine
    container_name: smarttasker-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - smarttasker-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Redis Commander - Redis Admin Interface
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: smarttasker-redis-commander
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=password
    networks:
      - smarttasker-network
    depends_on:
      - redis
    restart: unless-stopped

networks:
  smarttasker-network:
    driver: bridge

volumes:
  redis_data: 